# Example Render configuration. You will need to adjust this for the different services you run.
# Replace repo url with the repository url for your Jumpstart Pro application
services:
  - type: web
    repo: https://github.com/nipunhsud/ai-agents.git # Replace this url
    name: ai-agents
    env: python
    region: oregon # the region must be consistent across all services for the internal keys to be read
    buildCommand: "./build.sh"
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString


  # Uncomment the following blueprint if you want to enable a background worker
  # - type: worker
  #   name: sidekiq-worker
  #   env: ruby
  #   plan: starter # no free option for bg workers
  #   region: oregon # the region must be consistent across all services for the internal keys to be read
  #   buildCommand: "./bin/render-build.sh"
  #   startCommand: bundle exec sidekiq -e production
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: postgres
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         name: redis
  #         type: redis
  #         property: connectionString
  #     - key: RAILS_MASTER_KEY
  #       sync: false

databases:
  - name: postgres
    region: virginia # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections

