# Generated by Django 5.1.3 on 2025-01-06 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_value', models.CharField(help_text='8-character unique identifier', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)])),
                ('username', models.CharField(help_text='Username for API access', max_length=150)),
                ('secret_key', models.CharField(help_text='GitHub API token', max_length=255)),
                ('github_api', models.CharField(help_text='GitHub API token', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
